### ISSUE TITLE
About distance measurement

### ISSUE THREAD

**Issue by shliang0603** [pattylo/Autonomous-Object-Tracking-UAV-System#1]
@pattylo Hi,  I have seen your demo, I want to know how you realize the judgment of the detection target distance, do you use any sensor？

**Comment by pattylo** [comment]
Hi thank you for your question. Yes in fact, I had been using RealSense D435i for simplicity, as the camera could directly give you the depth information. Below are the link of the RealSense camera SDK and the ros-wrapper of realsense cameras:

https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md
https://github.com/IntelRealSense/realsense-ros

hope that answer your question :)

**Comment by shliang0603** [comment]
OK, thanks for your reply
