### ISSUE TITLE
找不到offb/obj.h

### ISSUE THREAD

**Issue by chengziYing** [pattylo/Autonomous-Object-Tracking-UAV-System#2]
/home/nvidia/AUTO/src/AUTO-master/offb/src/camera.cpp:14:10: fatal error: offb/obj.h: 没有那个文件或目录
 #include "offb/obj.h"
          ^~~~~~~~~~~~
compilation terminated.
AUTO-master/offb/CMakeFiles/camera.dir/build.make:62: recipe for target 'AUTO-master/offb/CMakeFiles/camera.dir/src/camera.cpp.o' failed
make[2]: *** [AUTO-master/offb/CMakeFiles/camera.dir/src/camera.cpp.o] Error 1
CMakeFiles/Makefile2:1874: recipe for target 'AUTO-master/offb/CMakeFiles/camera.dir/all' failed
make[1]: *** [AUTO-master/offb/CMakeFiles/camera.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....

**Comment by pattylo** [comment]
may I ask which version of ubuntu are you using?
make sure that the msg file including obj.msg is in the directory 

you can also check CMakelists.txt as well as package.xml for message_generation-related lines, whether they are all properly placed.

**Comment by chengziYing** [comment]
> 

yes,CMakelists.txt and package.xml doesn't contain message_generation-related lines, like "message_generation" from find_package, and" message_generation message_runtime" in catkin_package, so obj.h doesn't been generated.

And after that, when I rosrun offb camera and offb track , I find  "mydnn.forward(netOutput, net_outputNames);" from run_yolo.cpp can't generate output  "netOutput" so that object like human cannot be detected. 

net_outputNames contain"yolo_30 and yolo_37" in yolo_tiny has been affirmed.

**Comment by chengziYing** [comment]
result like this:

480 x 640
affirm whether been here : *****************01
names:yolo_30
names:yolo_37
time:0.581299
fps: 1.72028
affirm whether been here : *****************03
output structure: [8 x 1083]
affirm whether been here : *****************03
output structure: [8 x 4332]
fps: 1.6777
fps_avg: 1.5862
temp size: 0
ms: 0.596512
notFoundCount:19
show predict

object: 0
X_c: 0
Y_c: 0
Z_c: 0


480 x 640
affirm whether been here : *****************01
names:yolo_30
names:yolo_37
^Ctime:0.600099
fps: 1.66639
affirm whether been here : *****************03
output structure: [8 x 1083]
affirm whether been here : *****************03
output structure: [8 x 4332]
fps: 1.62726
fps_avg: 1.58826
temp size: 0
ms: 0.614944
notFoundCount:20
show predict

object: 0
X_c: 0
Y_c: 0
Z_c: 0

**Comment by pattylo** [comment]
I've just tried it out, and the code should not be a problem. But please do make sure you have the correct version of opencv, the right path to cfg file and weight file.
