### ISSUE TITLE
How to solve the error: (-215:Assertion failed) src.channels() == 1 && src.dims == 2 in function 'findNonZero'`

### ISSUE THREAD

**Issue by pisces365** [pattylo/Autonomous-Object-Tracking-UAV-System#3]
Hi there, when I try to run those command below
`rosrun offb camera && rosrun offb track`
the system throw out the exception like this in run_yolo.cpp line 166 `cv::findNonZero(ROIframe, nonzeros);`

`360 x 640
time:0
fps: inf
call findNonZero
OpenCV(4.6.0-dev) /home/pisces/opencv/modules/core/src/count_non_zero.dispatch.cpp:160: error: (-215:Assertion failed) src.channels() == 1 && src.dims == 2 in function 'findNonZero'`

and I don't know what to do. Did you meet this problem when you make coding before?

Well, I guess it maybe caused by the camera type, but I'm not very sure. By the way,I run this code on simulation environment(XTDrone, gazebo).

So I hope you can help me to solve the problem.

thanks~

**Comment by pattylo** [comment]
for findNonZero function, make sure that your image have only 1 channel, whilst being 2 dimension. I am guessing that you might want to check your depth image, whether it fulfils the above condition. Hopt that this helps.

**Comment by pisces365** [comment]
> for findNonZero function, make sure that your image have only 1 channel, whilst being 2 dimension. I am guessing that you might want to check your depth image, whether it fulfils the above condition. Hopt that this helps.

Thank you very much, I'll give it a try.
